// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EventLink_Repositories.Models;

public partial class Conversation
{
    public Guid Id { get; set; }

    public Guid? PartnershipId { get; set; }

    public Guid CreatedByUserId { get; set; }

    public string Title { get; set; }

    public string ConversationType { get; set; }

    public DateTime? LastMessageAt { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }
}