// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EventLink_Repositories.Models;

public partial class DashboardMetric
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public DateOnly MetricDate { get; set; }

    public int? ProfileViews { get; set; }

    public int? MessagesReceived { get; set; }

    public int? MessagesSent { get; set; }

    public int? ActiveEvents { get; set; }

    public int? CompletedEvents { get; set; }

    public int? ActivePartnerships { get; set; }

    public int? CompletedPartnerships { get; set; }

    public decimal? AverageRating { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User User { get; set; }
}