// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EventLink_Repositories.Models;

public partial class EventProposal
{
    public Guid Id { get; set; }

    public Guid EventId { get; set; }

    public string ProposalType { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Requirements { get; set; }

    public decimal? Budget { get; set; }

    public DateTime? Deadline { get; set; }

    public string ContactInstructions { get; set; }

    public string AttachmentUrls { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Event Event { get; set; }
}