// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EventLink_Repositories.Models;

public partial class Event
{
    public Guid Id { get; set; }

    public Guid OrganizerId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string ShortDescription { get; set; }

    public DateTime? EventDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string Location { get; set; }

    public string VenueDetails { get; set; }

    public decimal? TotalBudget { get; set; }

    public int? ExpectedAttendees { get; set; }

    public string Category { get; set; }

    public string EventType { get; set; }

    public string TargetAudience { get; set; }

    public string RequiredServices { get; set; }

    public string SponsorshipNeeds { get; set; }

    public string SpecialRequirements { get; set; }

    public string Status { get; set; }

    public bool? IsPublic { get; set; }

    public bool? IsFeatured { get; set; }

    public string CoverImageUrl { get; set; }

    public string EventImages { get; set; }

    public int? ViewCount { get; set; }

    public int? InterestedCount { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<EventProposal> EventProposals { get; set; } = new List<EventProposal>();

    public virtual User Organizer { get; set; }

    public virtual ICollection<Partnership> Partnerships { get; set; } = new List<Partnership>();
}