// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EventLink_Repositories.Models;

public partial class Message
{
    public Guid Id { get; set; }

    public Guid SenderId { get; set; }

    public Guid ReceiverId { get; set; }

    public Guid? PartnershipId { get; set; }

    public string Content { get; set; }

    public string MessageType { get; set; }

    public string AttachmentUrl { get; set; }

    public string AttachmentName { get; set; }

    public bool? IsRead { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Partnership Partnership { get; set; }

    public virtual User Receiver { get; set; }

    public virtual User Sender { get; set; }
}