// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EventLink_Repositories.Models;

public partial class Partnership
{
    public Guid Id { get; set; }

    // ✅ CHANGED: Make EventId nullable
    public Guid? EventId { get; set; }

    public Guid PartnerId { get; set; }

    public string PartnerType { get; set; }

    // ✅ Explicitly nullable
    public string? InitialMessage { get; set; }

    // ✅ Explicitly nullable
    public string? OrganizerResponse { get; set; }

    public decimal? ProposedBudget { get; set; }

    public decimal? AgreedBudget { get; set; }

    // ✅ Explicitly nullable
    public string? ServiceDescription { get; set; }

    // ✅ Explicitly nullable
    public string? Status { get; set; }

    // ✅ Explicitly nullable
    public string? OrganizerContactInfo { get; set; }

    // ✅ Explicitly nullable
    public string? PartnerContactInfo { get; set; }

    // ✅ Explicitly nullable
    public string? PreferredContactMethod { get; set; }

    // ✅ Explicitly nullable
    public string? ExternalWorkspaceUrl { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? DeadlineDate { get; set; }

    public DateTime? CompletionDate { get; set; }

    // ✅ Explicitly nullable
    public string? OrganizerNotes { get; set; }

    // ✅ Explicitly nullable (already updated before)
    public string? PartnershipImage { get; set; }

    // ✅ Boolean nullable (changed from SharedNotes)
    public bool? IsMark { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    // ✅ CHANGED: Event navigation property is now nullable
    public virtual Event? Event { get; set; }

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual User Partner { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}

/// <summary>
/// Partnership Status - Workflow states
/// ✅ UPDATED: New status flow
/// </summary>
public static class PartnershipStatus
{

    public const string Pending = "Pending";
    public const string Ongoing = "Ongoing";
    public const string Completed = "Completed";
    public const string Cancelled = "Cancelled";
}

public static class PartnerType
{
    public const string Sponsor = "Sponsor";       
    public const string Supplier = "Supplier";     
    public const string Organizer = "Organizer";   
}

public static class ContactMethod
{
    public const string Email = "Email";           
    public const string Phone = "Phone";           
}