// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EventLink_Repositories.Models;

public partial class Partnership
{
    public Guid Id { get; set; }

    public Guid EventId { get; set; }

    public Guid PartnerId { get; set; }

    public string PartnerType { get; set; }

    public string InitialMessage { get; set; }

    public string OrganizerResponse { get; set; }

    public decimal? ProposedBudget { get; set; }

    public decimal? AgreedBudget { get; set; }

    public string ServiceDescription { get; set; }

    public string Status { get; set; }

    public string OrganizerContactInfo { get; set; }

    public string PartnerContactInfo { get; set; }

    public string PreferredContactMethod { get; set; }

    public string ExternalWorkspaceUrl { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? DeadlineDate { get; set; }

    public DateTime? CompletionDate { get; set; }

    public string OrganizerNotes { get; set; }

    public string PartnerNotes { get; set; }

    public string SharedNotes { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Event Event { get; set; }

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual User Partner { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}