// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EventLink_Repositories.Models;

public partial class Payment
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public Guid? SubscriptionId { get; set; }

    public string PaymentType { get; set; }

    public decimal Amount { get; set; }

    public string Currency { get; set; }

    public string PayOsorderId { get; set; }

    public string PayOstransactionId { get; set; }

    public string PaymentMethod { get; set; }

    public string Status { get; set; }

    public DateTime? PaymentDate { get; set; }

    public string Description { get; set; }

    public string PaymentGatewayResponse { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual UserSubscription Subscription { get; set; }

    public virtual User User { get; set; }
}