// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EventLink_Repositories.Models;

public partial class ProjectTask
{
    public Guid Id { get; set; }

    public Guid PartnershipId { get; set; }

    public Guid? AssignedToUserId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Priority { get; set; }

    public string Status { get; set; }

    public DateTime? DueDate { get; set; }

    public DateTime? CompletionDate { get; set; }

    public string AttachmentUrls { get; set; }

    public string CompletionNotes { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}