// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EventLink_Repositories.Models;

public partial class Review
{
    public Guid Id { get; set; }

    public Guid PartnershipId { get; set; }

    public Guid ReviewerId { get; set; }

    public Guid RevieweeId { get; set; }

    public int? OverallRating { get; set; }

    public int? CommunicationRating { get; set; }

    public int? QualityRating { get; set; }

    public int? TimelinessRating { get; set; }

    public int? ProfessionalismRating { get; set; }

    public string ReviewTitle { get; set; }

    public string ReviewComment { get; set; }

    public string Pros { get; set; }

    public string Cons { get; set; }

    public bool? WouldRecommend { get; set; }

    public bool? WouldWorkAgain { get; set; }

    public bool? IsPublic { get; set; }

    public bool? IsVerified { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Partnership Partnership { get; set; }

    public virtual User Reviewee { get; set; }

    public virtual User Reviewer { get; set; }
}