// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EventLink_Repositories.Models;

public partial class SponsorPackage
{
    public Guid Id { get; set; }

    public Guid SponsorId { get; set; }

    public string PackageName { get; set; }

    public string PackageType { get; set; }

    public decimal? Budget { get; set; }

    public string BudgetRange { get; set; }

    public string SponsorshipBenefits { get; set; }

    public string TargetAudience { get; set; }

    public string PreferredEventTypes { get; set; }

    public string BrandGuidelines { get; set; }

    public string LogoUrl { get; set; }

    public string BrandAssets { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User Sponsor { get; set; }
}