// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EventLink_Repositories.Models;

public partial class SubscriptionPlan
{
    public Guid Id { get; set; }

    public string PlanName { get; set; }

    public string PlanType { get; set; }

    public string TargetRole { get; set; }

    public decimal MonthlyPrice { get; set; }

    public decimal? YearlyPrice { get; set; }

    public int? MaxEvents { get; set; }

    public int? MaxPartnerships { get; set; }

    public int? MaxMessages { get; set; }

    public string Features { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<UserSubscription> UserSubscriptions { get; set; } = new List<UserSubscription>();
}