// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EventLink_Repositories.Models;

public partial class SupplierService
{
    public Guid Id { get; set; }

    public Guid SupplierId { get; set; }

    public string ServiceName { get; set; }

    public string ServiceCategory { get; set; }

    public string Description { get; set; }

    public decimal? BasePrice { get; set; }

    public string PriceUnit { get; set; }

    public decimal? MinPrice { get; set; }

    public decimal? MaxPrice { get; set; }

    public string ServiceImages { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User Supplier { get; set; }
}