// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EventLink_Repositories.Models;

public partial class UserActivity
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public string ActivityType { get; set; }

    public string EntityType { get; set; }

    public Guid? EntityId { get; set; }

    public string Description { get; set; }

    public string IpAddress { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User User { get; set; }
}