// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
// ✅ UPDATED: Added IsPremium fields for Premium subscription
#nullable disable
using System;
using System.Collections.Generic;

namespace EventLink_Repositories.Models;

public partial class User
{
    public Guid Id { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string Role { get; set; }

    public string FullName { get; set; }

    public string PhoneNumber { get; set; }

    public string AvatarUrl { get; set; }

    public bool? IsActive { get; set; }

    public bool? EmailVerified { get; set; }

    public DateTime? LastLoginAt { get; set; }

    // ✅ NEW: Premium Status Fields
    public bool? IsPremium { get; set; }

    public DateTime? PremiumExpiryDate { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    // Navigation properties
    public virtual ICollection<DashboardMetric> DashboardMetrics { get; set; } = new List<DashboardMetric>();

    public virtual ICollection<Event> Events { get; set; } = new List<Event>();

    public virtual ICollection<Message> MessageReceivers { get; set; } = new List<Message>();

    public virtual ICollection<Message> MessageSenders { get; set; } = new List<Message>();

    public virtual ICollection<Partnership> Partnerships { get; set; } = new List<Partnership>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<Review> ReviewReviewees { get; set; } = new List<Review>();

    public virtual ICollection<Review> ReviewReviewers { get; set; } = new List<Review>();

    public virtual ICollection<SponsorPackage> SponsorPackages { get; set; } = new List<SponsorPackage>();

    public virtual ICollection<SupplierService> SupplierServices { get; set; } = new List<SupplierService>();

    public virtual ICollection<UserActivity> UserActivities { get; set; } = new List<UserActivity>();

    public virtual ICollection<UserProfile> UserProfiles { get; set; } = new List<UserProfile>();

    public virtual ICollection<UserSubscription> UserSubscriptions { get; set; } = new List<UserSubscription>();

    public virtual ICollection<BrandProfile> BrandProfiles { get; set; } = new List<BrandProfile>();

    // ✅ NEW: Helper method to check active premium status
    public bool IsActivePremium()
    {
        return IsPremium == true &&
               PremiumExpiryDate.HasValue &&
               PremiumExpiryDate.Value > DateTime.UtcNow;
    }
}